baseURL: https://synergymetrics.github.io/Ipac-Nexus/
languageCode: en-us
title: Nexus - Model
theme: github.com/google/docsy
params:
  copyright: © 2025 Nexus - Model
  gtm_enabled: false
  ui:
    sidebar_menu_compact: true
    navbar_logo: true
    footer_edit_page: false
module:
  imports:
    - path: github.com/google/docsy
    - path: github.com/google/docsy/dependencies
menus:
  main:
    - name: Home
      url: /
      weight: 10
    - name: Q&A
      url: /docs/qa/
      weight: 20
    - name: Explanations
      url: /docs/explanations/
      weight: 30
  #  - name: About
  #    url: /docs/about/
  #    weight: 40
  #  - name: Blog
  #    url: /blog/
  #    weight: 50
